ports:
  http:
    port: 8020

volumes:
  - name: data
    emptyDir: {}

volumeMounts:
  - name: data
    mountPath: /db

ingress:
  enabled: true
  rules:
    http: /v1/rkn
  annotations:
    kubernetes.io/ingress.class: nginx

livenessProbe:
  httpGet:
    path: /_liveness
    port: http
    scheme: HTTP
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 11

readinessProbe:
  httpGet:
    path: /_readiness
    port: http
    scheme: HTTP
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1